server:
    port: 9083
spring: 
    application:
        name: tcc-user-service
    datasource: 
        url: jdbc:mysql://localhost:3306/tcc_user?&useSSL=false&characterEncoding=UTF-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    redis:
        host: localhost
        port: 6379
        database: 1
        pool:
            maxActive: 2
jfish: 
    mq:
        transactional:
            enabled: true
            sendTask:
                enabled: true
    ons:
        serverType: rocketmq
        onsAddr: localhost:10911
        #serializer: TYPING_JSON
        namesrvAddr: localhost:9876
    redis: 
        lock-registry: 
            key: ${spring.application.name}
    tcc: 
        publish-txlog: true
        compensation: 
            use-reids-lock: true